---
- name: "Create VirtualHosts in 'virtualhosts.conf'"
  tags: httpd.config.vhost
  ansible.builtin.template:
    src: virtualhosts.ji2
    dest: /etc/httpd/conf.d/virtualhosts.conf
    group: apache
    mode: 0644
    setype: httpd_config_t
  notify: "Restart httpd service"

- name: "Set 'Listen' ports in 'httpd.conf'"
  tags: httpd.config.httpd
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: "Listen"
    line: "Listen {{ item }}"
    validate: httpd -t -f %s
  loop: "{{ httpd_VirtualHosts | map(attribute='Listen') | list }}"
  notify: "Restart httpd service"
