- name: "Allow ports in SELinux"
  tags: apache-config-seport
  community.general.seport:
    ports: "{{ item | string }}"
    proto: tcp
    setype: http_port_t
  loop: "{{ apache_VirtualHosts | map(attribute='Listen') | list }}"

- name: "Create VirtualHosts in 'virtualhosts.conf'"
  tags: apache-config-vhost
  template:
    src: virtualhosts.ji2
    dest: /etc/httpd/conf.d/virtualhosts.conf
    group: apache
    mode: 0644
    setype: httpd_config_t
  notify: "Restart httpd service"

- name: "Set 'Listen' ports in 'httpd.conf'"
  tags: apache-config-httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: "Listen"
    line: "Listen {{ item }}"
    validate: httpd -t -f %s
  loop: "{{ apache_VirtualHosts | map(attribute='Listen') | list }}"
  notify: "Restart httpd service"
