- name: "Allow services in firewall"
  tags: services
  firewalld:
    service: "{{ item[1] }}"
    state: enabled
    permanent: yes
    immediate: yes
    zone: "{{ item[0]['name'] }}"
  loop: "{{ firewalld['zones'] | subelements('services') }}"

- name: "Allow ports in firewall"
  tags: ports
  firewalld:
    port: "{{ item[1] }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
    zone: "{{ item[0]['name'] }}"
  loop: "{{ firewalld['zones'] | subelements('ports') }}"

- name: "Allow ports in SELinux"
  tags: selinux
  seport:
    ports: "{{ item | string }}"
    proto: tcp
    setype: http_port_t
  loop: "{{ firewalld['zones'] | map(attribute='ports') | flatten | unique }}"
