---
- name: "Configure httpd server"
  tags:
    - httpd
    - httpd.config
  ansible.builtin.import_tasks: config.yaml

- name: "Configure SELinux for httpd server"
  tags:
    - httpd
    - httpd.selinux
  ansible.builtin.import_tasks: selinux.yaml
  when: ansible_os_family in ['RedHat','Debian']
