- name: "Configure httpd server"
  tags:
  - apache
  - apache-config
  import_tasks: config.yml

- name: "Configure SELinux for httpd server"
  tags:
  - apache
  - apache-selinux
  import_tasks: selinux.yml
