---
- name: "Configure httpd server"
  tags:
    - apache
    - apache.config
  ansible.builtin.import_tasks: config.yml

- name: "Configure SELinux for httpd server"
  tags:
    - apache
    - apache.selinux
  ansible.builtin.import_tasks: selinux.yml
