- name: "Allow ports in SELinux"
  community.general.seport:
    ports: "{{ item | string }}"
    proto: tcp
    setype: http_port_t
  loop: "{{ apache_VirtualHosts | map(attribute='Listen') | list }}"

